# Generated by Django 5.1 on 2024-08-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_status_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='facebook_profile',
        ),
        migrations.RemoveField(
            model_name='users',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='users',
            name='twitter_handle',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
