# Generated by Django 5.1 on 2024-08-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_users_facebook_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
